ALTER TABLE users ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ip_country TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ip_city TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ip_region TEXT;
